### ISSUE TITLE
Support LND as LN backend

### ISSUE THREAD

**Issue by prusnak** [cashubtc/cdk#301]
Title says it all.

It seems there are multiple forks of crates which can be used to access LND: https://crates.io/search?q=lnd

I think these two might be worth investigating:
* https://crates.io/crates/fedimint-tonic-lnd
* https://crates.io/crates/lnd_grpc_rust

**Comment by thesimplekid** [comment]
I don't have direct experience with either and they both seem like they would cover our needs of interacting with LND for the mint. Since fedimint is a project I know better and their primary gateway target is lnd I would imagine that crate to be well maintained so I would have a mild preference towards the `fedimint-tonic-lnd` based on that.

**Comment by prusnak** [comment]
Moksha code for reference: https://github.com/ngutech21/moksha/blob/master/moksha-mint/src/lightning/lnd.rs

It also uses `fedimint-tonic-lnd`.
