### ISSUE TITLE
Mint SQL Database 

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#74]
- [ ] SQLite

**Comment by lorenzolfm** [comment]
Have you give any though about what crate should this project use handle the db stuff?

AFAIK there are two major crates for that: [sqlx](https://github.com/launchbadge/sqlx) and [diesel](https://github.com/diesel-rs/diesel). Both support SQLlite and Postgres.

I'm more familiar with diesel, that's what I use in my daytime job. Diesel is an ORM, db queries look like this:

```rust
let versions = Version::belonging_to(krate)
  .select(id)
  .order(num.desc())
  .limit(5);
let downloads = version_downloads
  .filter(date.gt(now - 90.days()))
  .filter(version_id.eq_any(versions))
  .order(date)
  .load::<Download>(&mut conn)?;
  ```
  It's also very fast compared to other crates (see: https://github.com/diesel-rs/metrics). By the way, this metrics repo also has comparisons between sqlite and postgres.
  
 The downsides are the error messages, which sometimes are honestly disgusting.
  
 I can't talk much about sqlx. All that I known is that it has compile-time verification for queries and it's not an ORM, so queries look like normal sql queries written inside macros:
 
 ```rust
 let countries = sqlx::query!(
        "
SELECT country, COUNT(*) as count
FROM users
GROUP BY country
WHERE organization = ?
        ",
        organization
    )
    .fetch_all(&pool) // -> Vec<{ country: String, count: i64 }>
    .await?;
```

I'm obviously biased towards diesel, since I only have xp with it. I'm interested to read your thoughts on this.

Also, I think this is more important of a decision and will affect the project more than what db should we use. In that matter tho, I think it's probably best to start with sqlite because its simpler. There's no reason to not support both in the future if needed.

**Comment by thesimplekid** [comment]
Thanks for posting this is a good thing to discuss that I've thought a bit about but don't have direct experience with either. 

In general I think ORMs like diesel, while they provide some nice conveniences they're an unnecessary abstraction, over something like SQLx where SQL can be used. Using an ORM means using the ORM's specific syntax and hiding the true SQL that is generated and run. 

Though the syntax of diesel is a bit nicer and the the speed of the crate is compelling at least on those metrics.

To avoid the abstraction i lean towards not using an ORM and using sqlx but certainly open to hearing more thoughts on it.

**Comment by lorenzolfm** [comment]
That's a fair point. SQLx is fine by me
